import { FormInterface } from "../compact/types";

export const CONTROL_OPTIONS_STATIC_FORM: FormInterface = {
  id: 0,
  title: "AJOUT DE D'UNE CONFIGURATION DE D'OPTION DE CHAMPS DE SÉLECTION",
  description:
    "Remplir les champs ci-dessous pour ajouter une nouvelle configuration d'options de champe de selection.",
  controls: [
    {
      id: 1,
      label: "Namespace Model",
      placeholder: "Saisir..",
      type: "text",
      classes: "clr-input",
      required: false,
      disabled: false,
      readonly: false,
      unique: true,
      pattern: undefined,
      description: "modelNamespaceDescriptionText",
      maxLength: 1024,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "model",
      controlIndex: 1,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
    {
      id: 2,
      label: "Table (BD)",
      placeholder: "Saisir...",
      type: "text",
      classes: "clr-input",
      required: true,
      disabled: false,
      readonly: false,
      unique: true,
      pattern: undefined,
      description: "tableDescriptionText",
      maxLength: 45,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "table",
      controlIndex: 2,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
    {
      id: 3,
      label: "Champ d'indexation",
      placeholder: "Saisir...",
      type: "text",
      classes: "clr-input",
      required: true,
      disabled: false,
      readonly: false,
      unique: false,
      pattern: undefined,
      description: "keyfieldDescriptionText",
      maxLength: 45,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "keyfield",
      controlIndex: 4,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
    {
      id: 4,
      label: "Champ libellé",
      placeholder: "Saisir...",
      type: "text",
      classes: "clr-input",
      required: true,
      disabled: false,
      readonly: false,
      unique: false,
      pattern: undefined,
      description: "valuefieldDescriptionText",
      maxLength: 45,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "valuefield",
      controlIndex: 5,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
    {
      id: 5,
      label: "Champ de regroupement",
      placeholder: "Saisir...",
      type: "text",
      classes: "clr-input",
      required: true,
      disabled: false,
      readonly: false,
      unique: false,
      pattern: undefined,
      description: "groupfieldDescriptionText",
      maxLength: 45,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "groupfield",
      controlIndex: 6,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
    {
      id: 6,
      label: "Libellé",
      placeholder: "Saisir...",
      type: "text",
      classes: "clr-input",
      required: true,
      disabled: false,
      readonly: false,
      unique: false,
      pattern: undefined,
      description: "displayLabelDescriptionText",
      maxLength: 190,
      minLength: 1,
      min: undefined,
      max: undefined,
      minDate: undefined,
      maxDate: undefined,
      selectableValues: undefined,
      selectableModel: undefined,
      multiple: false,
      options: undefined,
      controlGroupKey: undefined,
      controlName: "display_label",
      controlIndex: 3,
      columns: undefined,
      rows: undefined,
      value: undefined,
    },
  ],
  url: undefined,
};
