export const FORM_RESOURCES_PATH = 'FORM_RESOURCES_PATH';
export const FORM_CONTROL_RESOURCES_PATH = 'FORM_CONTROL_RESOURCES_PATH';
export const CONTROL_OPTION_RESOURCES_PATH = 'CONTROL_OPTION_RESOURCES_PATH';
export const CONTROL_BINDINGS_RESOURCES_PATH = 'CONTROL_BINDINGS_RESOURCES_PATH';
export const FORM_FORM_CONTROL_RESOURCES_PATH = 'FORM_FORM_CONTROL_RESOURCES_PATH';